plugins {
    id 'fabric-loom' version '1.13.6'
    id 'maven-publish'
}
version = '2.3.9'
group = 'com.autosprint'
repositories {
    maven {
        name = "Fabric"
        url = "https://maven.fabricmc.net/"
    }
    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/releases/"
    }
}
dependencies {
    minecraft 'com.mojang:minecraft:1.21.4'
    mappings 'net.fabricmc:yarn:1.21.4+build.8:v2'
    modImplementation 'net.fabricmc:fabric-loader:0.17.2'
    modImplementation 'net.fabricmc.fabric-api:fabric-api:0.119.4+1.21.4'
    modImplementation "com.terraformersmc:modmenu:13.0.3"
}
processResources {
    inputs.property 'version', version
    filesMatching('fabric.mod.json') {
        expand 'version': version
    }
}
tasks.withType(JavaCompile).configureEach {
    options.release = 21
}
java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
jar {
    from('LICENSE') {
        rename { "${it}_${base.archivesName.get()}" }
    }
}